services:
  timeseries-api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - DATABASE_HOST=postgres
    ports:
      - '8080:80'
      - '2112:2112' # Metrics
    volumes:
      - .env:/project/.env
    depends_on:
      - postgres
  postgres:
    image: timescale/timescaledb:latest-pg16
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/postgresql/data/pgdata
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '${DATABASE_PORT:-5432}:5432'
  redis:
    image: redis:latest
    restart: unless-stopped
    ports:
      - '${REDIS_PORT:-6379}:6379'

volumes:
  db_data:
